# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deisgn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from time import sleep
from random import randint

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 486)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 180, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(52, 141, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 300, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(242, 141, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 180, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.lineEdit.setText(_translate("MainWindow", "pessoa 1"))
        self.label_2.setText(_translate("MainWindow", "01"))

        self.lineEdit_2.setText(_translate("MainWindow", "pessoa 2"))
        self.label_3.setText(_translate("MainWindow", "01"))
        
        self.pushButton.setText(_translate("MainWindow", "SORTEAR"))


        # disputa 1
        self.pushButton.clicked.connect(self.sortear1)


    # disputa 1
    def sortear1(self):
        
        self.label_2.setText(str(0))
        self.label_3.setText(str(0))
        self.pushButton.setDisabled(True)

        # animacao
        # for i in range(3):
        #     sorteado1 = randint(1, 75)
        #     sorteado2 = randint(1, 75)
        #     self.label_2.setText(str(sorteado1))
        #     self.label_3.setText(str(sorteado2))
        #     QtWidgets.QApplication.processEvents()

        #     sleep(0.2+(i/2))


# sorteia 2 numeros de 0 à 75
        sorteado1 = randint(1, 75)
        sorteado2 = randint(1, 75)
        while sorteado1 == sorteado2:
            sorteado2 = randint(1, 75)
        
        self.label_2.setText(str(sorteado1))
        self.label_3.setText(str(sorteado2))

        self.pushButton.setDisabled(False)



if __name__ == "__main__":
    # qntDisputa = input('Abrir disputa entre quantos jogadores? ')

    import ctypes
    ctypes.windll.user32.ShowWindow( ctypes.windll.kernel32.GetConsoleWindow(), 0 )
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    # atualizacao()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())